#undef TAPPING_TERM
#define TAPPING_TERM 150

#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 300000

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 16

#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 8

#define USB_POLLING_INTERVAL_MS 10
#define SERIAL_NUMBER "eLXDW/PBwj5X"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

